### ISSUE TITLE
Changelog file.

### ISSUE THREAD

**Issue by Christophe31** [fcurella/python-datauri#17]
What do we get when we upgrade? Is there any python version support changes? Is there some api new features or changes? Can I break my code by upgrading this lib? If yes, what should I check first?

I didn't saw the changelog so I felt I had to look at the last commits messages one by one to feel there are no major changes here…

**Comment by fcurella** [comment]
Added in https://github.com/fcurella/python-datauri/commit/fc9f40f92491f80a9263c4aae8dba46997be2418
