### ISSUE TITLE
how do you actually convert the DataURI class to text that can be sent to browser?

### ISSUE THREAD

**Issue by tommyjcarpenter** [fcurella/python-datauri#2]
DataURI.Make(....) produces a class of type DataURI. I don't see any methods of then taking that to a bytestring that can be sent to the browser.

**Comment by fcurella** [comment]
The `DataURI` class is a subclass of `str`, so you can just send that. If you need bytes instead of a string, you can convert it with `my_datauri.encode()`

**Comment by tommyjcarpenter** [comment]
Got it, thanks! This library is very useful, thank you.
