### ISSUE TITLE
encoding bug in .from_file()

### ISSUE THREAD

**Issue by qingwang237** [fcurella/python-datauri#3]
https://github.com/fcurella/python-datauri/blob/0e8c0aeaecc2a265aa9c2a3578397bc45c5fb7a5/datauri/__init__.py#L68

I think it should be ```open(..., encoding=charset)``` otherwise the file encoded in other codes than utf-8 cannot be opened in the first place.

**Comment by fcurella** [comment]
The issue is that it's opening the file in text mode, when it should always be opening it in binary and convert only in `.text`
